Upload trivy results as artifacts

diff --git a/.github/workflows/build-image.yaml b/.github/workflows/build-image.yaml
--- a/.github/workflows/build-image.yaml
+++ b/.github/workflows/build-image.yaml
@@ -96,6 +96,7 @@ jobs:
 
   trivy:
     name: Scan image for fixable vulnerabilities
+    if: ${{ github.event_name == 'pull_request' }}
 
     needs: build
     runs-on: ubuntu-latest
@@ -113,25 +114,49 @@ jobs:
           IMAGE: ${{ fromJSON(needs.build.outputs.refs)[0] }}
 
       - name: Run Trivy vulnerability scanner
+        id: trivy
         uses: aquasecurity/trivy-action@master
+        continue-on-error: true
         with:
           image-ref: ${{ fromJSON(needs.build.outputs.refs)[0] }}
           exit-code: '1'
-          ignore-unfixed: true
+          output: trivy.txt
 
-      - name: Run Trivy vulnerability scanner
+
+      - name: Run Trivy vulnerability scanner (JSON results)
         uses: aquasecurity/trivy-action@master
         with:
           image-ref: ${{ fromJSON(needs.build.outputs.refs)[0] }}
-          exit-code: '1'
+          format: table
+          output: trivy.json
+
+      - name: Upload Trivy results (table)
+        uses: actions/upload-artifact@v2
+        with:
+          name: trivy-results
+          path: |
+            trivy.txt
+            trivy.json
+          retention-days: ${{ needs.build.outputs.stable == 'true' && 90 || 5 }}
+
+      - name: Run Trivy vulnerability scanner (**fixable**)
+        if: ${{ needs.build.outputs.stable == 'true' }}
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: ${{ fromJSON(needs.build.outputs.refs)[0] }}
           ignore-unfixed: true
           format: template
           template: '@/contrib/sarif.tpl'
-          output: trivy-results.sarif
+          output: trivy.sarif
 
-      - name: Upload results to GitHub Code Scanning
+      - name: Upload fixable Trivy vulnerabilities to GitHub Code Scanning
+        if: ${{ hashFiles('trivy.sarif') != ''}}
         uses: github/codeql-action/upload-sarif@v1
-        if: ${{ always() && hashFiles('trivy-results.sarif') != ''}}
         with:
-          sarif_file: trivy-results.sarif
+          sarif_file: trivy.sarif
 
+      - name: Check if scans found vulnerabilities
+        if: ${{ steps.trivy.outcome == 'failure' }}
+        run: |
+          echo "::error::Trivy scan found vulnerabilities"
+          exit 1
